### ISSUE TITLE
Suggestion for getting CPU Load info

### ISSUE THREAD

**Issue by bdarfler** [jrochkind/fake_work_app#4]
Check out this Heroku Labs plugin

https://devcenter.heroku.com/articles/log-runtime-metrics

Sorry for opening a ticket, I couldn't find any other way of contacting you. Cannot comment on the HN thread and couldn't find an active Twitter account.

**Comment by jrochkind** [comment]
Yep, I don't have a twitter account. No problem. 

That looks interesting. I'm probably not going to at the moment, but if you end up running the code with it, let us know what you find out!
