### ISSUE TITLE
rainbows! missing from comparison

### ISSUE THREAD

**Issue by viktors** [jrochkind/fake_work_app#6]
Sorry, comments are closed on HN. 

Very nice comparison!

It would be nice to have a comparison with Rainbows! with ThreadPool model, if possible - in my tests using Sinatra it slightly outperformed Puma on MRI (specifically, slowest requests were faster). A starting point could be to get unicorn configuration file and add something like this:

``` ruby
Rainbows! do
  use :ThreadPool
  worker_connections 5
end
```

**Comment by jrochkind** [comment]
I am personally done doing this kind of testing at the moment, but please feel free to fork this repo and test rainbows!  If you do, I would love to hear about it!
