### ISSUE TITLE
Benchmark request

### ISSUE THREAD

**Issue by dougc84** [jrochkind/fake_work_app#7]
Passenger 5 is the new hotness, and boasts some pretty impressive stats.  Can you add a benchmark for Passenger 5?

**Comment by jrochkind** [comment]
I'd be happy to merge in a Pull Request that adds it! You are also welcome to fork this code and do what you like with it.

**Comment by jrochkind** [comment]
I would expect the Enterprise version would do quite well, mainly what I think these benchmarks show is that for real apps that wait on I/O, multi-threaded request handling is the way to go, and Passenger Enterprise does support that. 

The free version of Passenger does not, so I would expect it do similarly to other app servers that do not, as well.
